server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service              #动态匹配
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2023-11-20T17:38:13.586918800+08:00[Asia/Shanghai] #在特定时间后才能访问
            - Cookie=username,zzyy
            - Header=X-Request-Id, \d+              # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            - Host=**.atguigu.com                   # 请求头Host主机地址后面必须这个
            - Query=username, \d+                   # 请求路径要有参数名username并且值还要是整数才能路由http://localhost:9527/pay/gateway/get/1?username=1
            - RemoteAddr=192.168.124.1/24           # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
            - Method=Get,Post


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service              #动态匹配
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
