server:
  port: 80

spring:
  application:
    name: cloud-consumer-openfeign-order
  ####Spring Cloud Consul for Service Discovery
  cloud:
    openfeign:
      client:
        config:
          #for all
#         default:
#           connect-timeout: 3000
#           read-timeout: 3000
          #for specific one higher priority
         cloud-payment-service:
           connect-timeout: 5000
           read-timeout: 5000
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}